# -*- mode: ruby -*-
# vi: set ft=ruby :

# Generate keys and copy public keys for docker machine to find.
if not File.exists?('docker_key') then 
   system("ssh-keygen -b 4096 -f docker_key -P ''") 
   system("cp docker_key.pub docker/")   
end
if not File.exists?('host_key') then
   system("ssh-keygen -b 4096 -f host_key -P ''") 
   system("cp host_key.pub docker/")   
end

# Always copy open script, might have changed in git. Symlink will not do with
# mounted dirs.
system("cp `which ../open` docker/open")

# Be careful to choose IPs that do not interfere with the eth0 IPs.
nodejsip = '192.168.2.37'
dockerip = '192.168.2.42'


# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.define "nodejs" do |nodejs|
     nodejs.vm.provider "virtualbox" do |v|
       # v.gui = true
       v.cpus = 2
       v.memory = 2048
     end
     nodejs.vm.network :private_network, ip: nodejsip, virtualbox__intnet: "internal"
     nodejs.vm.hostname = "nodejs"
     nodejs.vm.box = "ubuntu/trusty64"
     nodejs.vm.synced_folder "../", "/home/vagrant/InteractiveShell"
     nodejs.vm.synced_folder ".", "/vagrant", disabled: true
     nodejs.vm.network "forwarded_port", guest: 22, host: 4998, id: 'ssh'
     nodejs.vm.network "forwarded_port", guest: 8002, host: 3690
     nodejs.vm.provision "shell", privileged:false, inline: <<-SHELL
       sudo apt-get update
       sudo apt-get upgrade -y
       sudo apt-get install -y nodejs npm wget git
       sudo ln -s /usr/bin/nodejs /usr/bin/node
       sudo chown -R vagrant:vagrant /home/vagrant/InteractiveShell
       sudo cp /home/vagrant/InteractiveShell/separate_machines/docker/sshd_config /etc/ssh/sshd_config
       sudo chown root:root /etc/ssh/sshd_config
       sudo chmod 600 /etc/ssh/sshd_config
       sudo cp /home/vagrant/InteractiveShell/separate_machines/docker/ssh_config /etc/ssh/ssh_config
       sudo chown root:root /etc/ssh/ssh_config
       sudo chmod 644 /etc/ssh/ssh_config
       mkdir webm2.logs
       cd InteractiveShell
       npm install
     SHELL
  end

  config.vm.define "docker" do |docker|
     docker.vm.network :private_network, ip: dockerip, virtualbox__intnet: "internal"
     docker.vm.provider "virtualbox" do |v|
       # v.gui = true
       v.cpus = 4
       v.memory = 10000
     end
     docker.vm.hostname = "docker"
     docker.vm.box = "ubuntu/trusty64"
     docker.vm.synced_folder "./docker", "/home/vagrant/docker"
     docker.vm.synced_folder ".", "/vagrant", disabled: true
     docker.vm.network "forwarded_port", guest: 22, host: 4999, id: 'ssh'
     # for i in 5000..6000
     #    docker.vm.network :forwarded_port, guest: i, host: i
     # end
     docker.vm.provision "shell", privileged:false, inline: <<-SHELL
       export DEBIAN_FRONTEND=noninteractive
       sudo apt-get update 
       sudo apt-get upgrade -y
       echo iptables-persistent iptables-persistent/autosave_v4 boolean true | sudo debconf-set-selections
       echo iptables-persistent iptables-persistent/autosave_v6 boolean true | sudo debconf-set-selections
       sudo apt-get install -y wget iptables-persistent
       wget -qO- https://get.docker.com/ | sh
       cd docker
       cat /home/vagrant/docker/host_key.pub >> /home/vagrant/.ssh/authorized_keys
       sudo cp /home/vagrant/docker/sshd_config /etc/ssh/sshd_config
       sudo chown root:root /etc/ssh/sshd_config
       sudo chmod 600 /etc/ssh/sshd_config
       sudo cp /home/vagrant/docker/ssh_config /etc/ssh/ssh_config
       sudo chown root:root /etc/ssh/ssh_config
       sudo chmod 644 /etc/ssh/ssh_config
       sudo docker build -t m2container .
       sudo iptables -I DOCKER ! -d 192.168.2.37 -j DROP
       sudo iptables -I DOCKER ! -s 192.168.2.37 -j DROP
       sudo iptables -I DOCKER -d 192.168.2.37 -j ACCEPT
       sudo iptables -I DOCKER -s 192.168.2.37 -j ACCEPT
       sudo dpkg-reconfigure -fnoninteractive iptables-persistent
     SHELL
     # Last three lines need the nodejs IP from above, but this does not work
     # with verbatim mode.
  end 
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #

end
