#!/bin/sh
# Copyright © 2005-2013  Roger Leigh <rleigh@debian.org>
#
# schroot is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# schroot is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
#####################################################################

set -e

. "$SETUP_DATA_DIR/common-data"
. "$SETUP_DATA_DIR/common-functions"
. "$SETUP_DATA_DIR/common-config"

if [ "$VERBOSE" = "verbose" ]; then
    LVM_VERBOSE="-v"
fi

if [ "$CHROOT_TYPE" = "lvm-snapshot" ]; then

    if [ $STAGE = "setup-start" ]; then

        if [ ! "$DEVTYPE" "$CHROOT_DEVICE" ]; then
            fatal "Device '$CHROOT_DEVICE' does not exist"
        fi

        if [ "$VERBOSE" = "verbose" ]; then
            lvcreate $LVM_VERBOSE --snapshot --name "$CHROOT_LVM_SNAPSHOT_NAME" \
                "$CHROOT_DEVICE" $CHROOT_LVM_SNAPSHOT_OPTIONS
        else
            lvcreate $LVM_VERBOSE --snapshot --name "$CHROOT_LVM_SNAPSHOT_NAME" \
                "$CHROOT_DEVICE" $CHROOT_LVM_SNAPSHOT_OPTIONS > /dev/null
        fi

    elif [ $STAGE = "setup-stop" ]; then

        if [ "$DEVTYPE" "$CHROOT_LVM_SNAPSHOT_DEVICE" ]; then
            if [ "$VERBOSE" = "verbose" ]; then
                lvremove $LVM_VERBOSE -f "$CHROOT_LVM_SNAPSHOT_DEVICE" || true
            else
                lvremove $LVM_VERBOSE -f "$CHROOT_LVM_SNAPSHOT_DEVICE" > /dev/null || true
            fi
        else
            # The block device no longer exists, or was never created,
            # for example on lvcreate failure.
            warn "$CHROOT_LVM_SNAPSHOT_DEVICE does not exist (it may have been removed previously)"
        fi

    fi

fi

