#!/bin/sh
# Copyright © 2012-2013  Roger Leigh <rleigh@debian.org>
#
# schroot is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# schroot is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
#####################################################################

# Disassociates process execution context inside the chroot.
# If unsharing network CLONE_NEWNET, this has stopped all networking.
# We therefore need to bring up the lo interface to have working
# loopback.

set -e

. "$SETUP_DATA_DIR/common-data"
. "$SETUP_DATA_DIR/common-functions"
. "$SETUP_DATA_DIR/common-config"

if [ $STAGE = "exec-start" ]; then

    if [ "$UNSHARE_NEWNET" = "true" ]; then
        info "Bringing up netdev lo"
        ip link set dev lo up
    fi

fi

