#!/bin/sh

set -e

# Generate version information from git release tag

[ -f ./scripts/git-version ] && ./scripts/git-version > VERSION

# To satisfy automake
touch ChangeLog

# Bootstrap autotools
autoreconf --verbose --force --install

rm -rf autom4te.cache
rm -f config.h.in~
