all:
	M2 SimpledocToMarkdown.m2 -e "fileToMarkdown \"1-gettingStarted\"" -e "exit 0"
	M2 SimpledocToMarkdown.m2 -e "fileToMarkdown \"2-elementary-groebner\"" -e "exit 0"
	M2 SimpledocToMarkdown.m2 -e "fileToMarkdown \"3-beginningM2\"" -e "exit 0"

#mv 1-gettingStarted.md ../public/public-Macaulay2/tutorials/
#mv 2-elementary-groebner.md ../public/public-Macaulay2/tutorials/
#mv 3-beginningM2.md ../public/public-Macaulay2/tutorials/
