all:
	M2 DocConverter.m2 -e "convert \"1-gettingStarted\"" -e "exit 0"
	M2 DocConverter.m2 -e "convert \"2-elementary-groebner\"" -e "exit 0"
	M2 DocConverter.m2 -e "convert \"3-beginningM2\"" -e "exit 0"
	mv 1-gettingStarted.html ../public-Macaulay2/tutorials/
	mv 2-elementary-groebner.html ../public-Macaulay2/tutorials/
	mv 3-beginningM2.html ../public-Macaulay2/tutorials/
