#!/bin/sh
# Copyright © 2010-2013  Roger Leigh <rleigh@debian.org>
#
# schroot is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# schroot is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
#####################################################################

# Generate schroot usage profile

set -e

PROFILE="$1"
PLATFORM="$2"
SRCDIR="$3"
DESTDIR="$4"

[ -d "$DESTDIR" ] && rm -rf "$DESTDIR"
mkdir "$DESTDIR"

for file in copyfiles fstab nssdatabases; do
    for profile in all "$PROFILE"; do
        for arch in all "$PLATFORM"; do
            FILE="${SRCDIR}/${profile}/${arch}/${file}"
            if [ -f "$FILE" ]; then
                echo "Including $FILE"
                cat $FILE >> "${DESTDIR}/${file}"
            fi
        done
    done
    echo "Wrote ${DESTDIR}/${file}"
done
