.SH COPYRIGHT
Copyright \(co 2005\-2013  Roger Leigh \f[CR]<rleigh@debian.org>\fP
.PP
\fB\*[PROGRAM]\fP is free software: you can redistribute it and/or
modify it under the terms of the GNU General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.
